export global Theme {
    //add option to switch themes, managed by cpp??

    //colors
    out property <color> background: #5c3f97;
    out property <color> primary: #422c6e;
    out property <color> text-primary: #ffffff;
    out property <color> accent: #f1eaff;

    //player bar
    out property <color> text-muted: #8b7a9e;
    out property <color> icon-dim: #f1eaff;
    out property <color> bar-border: #7a62b3;
    out property <color> seek-track: #3a2f4f;
    out property <color> pink: #f7b9d4;
    out property <color> coral: #ff7b72;
}